apiVersion: v1
kind: Service
metadata:
  name: {{ include "amazingness-service.fullname" . }}
  labels:
    {{- include "amazingness-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-alg
      protocol: TCP
      name: http-alg
  selector:
    {{- include "amazingness-service.selectorLabels" . | nindent 4 }}
