apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazingness-service
  namespace: argocd # The namespace must match the namespace of your Argo CD instance.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/amazingitorg/charts
    targetRevision: <VERION>
    chart: amazingness-service
  destination:
    server: https://kubernetes.default.svc
    namespace: amazing
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
