apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-role
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "appprojects", "applicationsets/finalizers"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "get", "list", "patch", "watch"]
