apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-pod-read-only
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: runnersa
    namespace: self-hosted-runners
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
