apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
spec:
  replicas: 1
  template:
    spec:
      repository: AmazingITorg/amazingness-service
      serviceAccountName: runnersa
