name: Lock Service Testrun

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    
    - name: Unit Tests
      run: mvn test -Dtest=AmazingUnitTest
