name: Deploy Amazingness Service

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      version:
        description: New version number (e.g. 1.0.0)
        required: true
        
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
#       - uses: actions-hub/kubectl@master
#         env:
#           KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#         with:
#           args: get pods
      - name: folder
        run: mkdir ${HOME}/.kube
        
      - name: echo
        run: echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        
      - name: cat
        run: |
          cat ${HOME}/.kube/config
      
      - name: Use context
        run: kubectl config use-context minikube
      
      - name: Commands
        run: |
          kubectl get pods -n amazing
      
#     runs-on: self-hosted

#     steps:
#       - uses: actions/checkout@v3
      
#       - uses: azure/setup-kubectl@v2.0
#         id: install
        
#       - name: Set Version
#         run: |
#           sed -i -e "s/<VERSION>/${{ inputs.version }}/g" argocd/amazingness-service.yaml
#           cat argocd/amazingness-service.yaml
      
#       - name: Debug
#         run: |
#           kubectl get pods -n amazing
        
#       - name: Deploy app
#         run: |
#           kubectl apply -f "argocd/amazingness-service.yaml" -n argocd 
